var com_div=document.getElementById("commandiv");
function logout()
{
	window.localStorage.setItem("login","No");
	alert("You have Successfully Log Out")
}
if(localStorage.getItem("login")=="Yes")
{
	com_div.innerHTML='<div><img src="Pharmacylogo.jpg" style="width:8%;float:left;margin-left:10%;" alt="Pharmacylogos"><h1 style="text-align:center;float:left;padding-left:3%;">फार्मेसी <br/>PHARMACY</h1><img src="download(3).png" style="width:10%;float:right;margin-right:10%;margin-top:0%;" alt="img1"></div> <div class="topnav"><div class="search-container"><form action="action_page(1).php"><input type="text" placeholder="Search.." name="search"><button type="submit"><i class="fa fa-search"></i></button></form></div></div><br><br><br><br><br><br><br><br><div id="top_div" ><div class="display"><ul id="option_id" ><li class="option" class="display"><a href="home.html">Home</a></li><li class="option" class="display"><a href="Fitness.html">Fitness</a></li><div id="down" ><li  class="option" class="display"><a href="#">BabyCare</a></li><div class="dropdown"><ul type="square"><li><a href="Baby_Food.html">Baby Food</a></li><li><a href="Baby_Diapering.html">Diapering</a></li><li><a href="Baby_Personal_Care.html">Baby Personal Care</a></li></ul></div></div><div id="down"><li class="option" class="display"><a href="#">HomeEssentials </a></li><div class="dropdown" ><ul type="square"><li><a href="Covid_Essentials.html">Covid Essentials</a></li><li><a href="Insect_Killers.html">Insect Killers</a></li><li><a href="Antiseptic_Liquids.html">Antiseptic Liquids</a></li></ul></div></div><div id="down" ><li class="option" class="display"><a href="#">PersonalCare</a></li><div class="dropdown"><ul type="square"><li><a href="Skin_Care.html">Skin Care</a></li><li><a href="Hair_Care.html">Hair Care</a></li><li><a href="Oral_Care.html">Oral Care</a></li></ul></div></div><div id="down" ><li class="option" class="display"><a href="#">Corona</a></li><div class="dropdown" ><ul type="square"><li><a href="https://www.worldometers.info/coronavirus/">World</a></li><li><a href="https://www.worldometers.info/coronavirus/country/india/">India</a></li><li><a href="https://coronaclusters.in/madhya-pradesh">Madhya Pradesh</a></li></ul></div></div><div id="down" ><li class="option" class="display"><a href="#">Profile</a></li><div class="dropdown"><br><div id="profile">'+localStorage.getItem("Fname")+" "+localStorage.getItem("Lname")+'<br><span>'+localStorage.getItem("Username")+'<span></div><ul type="square"><li><a href="home.html" onclick="logout()">Log Out</a></li></ul></div></div>';

}
else
{
		com_div.innerHTML='<div><img src="Pharmacylogo.jpg" style="width:8%;float:left;margin-left:10%;" alt="Pharmacylogos"><h1 style="text-align:center;float:left;padding-left:3%;">फार्मेसी <br/>PHARMACY</h1><img src="download(3).png" style="width:10%;float:right;margin-right:10%;margin-top:0%;" alt="img1"></div> <div class="topnav"><div class="search-container"><form action="action_page(1).php"><input type="text" placeholder="Search.." name="search"><button type="submit"><i class="fa fa-search"></i></button></form></div></div><br><br><br><br><br><br><br><br><div id="top_div" ><div class="display"><ul id="option_id" ><li class="option" class="display"><a href="home.html">Home</a></li><li class="option" class="display"><a href="Fitness.html">Fitness</a></li><div id="down" ><li  class="option" class="display"><a href="#">BabyCare</a></li><div class="dropdown"><ul type="square"><li><a href="Baby_Food.html">Baby Food</a></li><li><a href="Baby_Diapering.html">Diapering</a></li><li><a href="Baby_Personal_Care.html">Baby Personal Care</a></li></ul></div></div><div id="down"><li class="option" class="display"><a href="#">HomeEssentials </a></li><div class="dropdown" ><ul type="square"><li><a href="Covid_Essentials.html">Covid Essentials</a></li><li><a href="Insect_Killers.html">Insect Killers</a></li><li><a href="Antiseptic_Liquids.html">Antiseptic Liquids</a></li></ul></div></div><div id="down" ><li class="option" class="display"><a href="#">PersonalCare</a></li><div class="dropdown"><ul type="square"><li><a href="Skin_Care.html">Skin Care</a></li><li><a href="Hair_Care.html">Hair Care</a></li><li><a href="Oral_Care.html">Oral Care</a></li></ul></div></div><div id="down" ><li class="option" class="display"><a href="#">Corona</a></li><div class="dropdown" ><ul type="square"><li><a href="https://www.worldometers.info/coronavirus/">World</a></li><li><a href="https://www.worldometers.info/coronavirus/country/india/">India</a></li><li><a href="https://coronaclusters.in/madhya-pradesh">Madhya Pradesh</a></li></ul></div></div><li class="option" class="display" id="ppp"><a href="login.html">Login</a></li></ul></div></div>';
}

document.getElementById("footer1").innerHTML='<div><h2>HELPLINE NUMBERS</h2><hr><ul><div class="inline_ul"><li><b>Child Helpline : 1098</b></li><li><b>Crime Stopper : 1090,100</b></li><li><b>NIC Service Desk :1800111555</b></li></div ><div class="inline_ul" style="padding-left:4%; float:left;"><li><b>Women Helpline : 1091</b></li><li><b>MP CM Help Line :181</b></li></div></ul></div><div class="author" style="margin-top:5%;"><address class="inline_ul" >Made By:<span color="red">@Shubham Farkya<br>@Nagendra Chouhana<br>@Yashwant Patidar</span></address></div><div class="author"><address>email <a href="email:ppharmacy@gmail.com">pharmacy@gmail.com</a><br>Visit us at: pharmacy.com<br>Mandsaur<br>Madhya Pradesh, India</address></div>'